# Generated by Django 5.2.3 on 2025-06-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entryexit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryexitrecord',
            options={'ordering': ['-timestamp'], 'permissions': [('export_entryexitrecord', 'Can export Entry Exit Record')], 'verbose_name': 'Entry Exit Record', 'verbose_name_plural': 'Entry Exit Records'},
        ),
    ]
