services:
  postgres:
    image: postgres
    container_name: postgres_container
    command: |
      -c 'max_connections=6000'
      -c logging_collector=on
      -c log_truncate_on_rotation=on
      -c log_directory='/var/log/postgresql'
      -c log_filename='postgresql-%m-%d.log'
      -c log_statement=all
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - postgres-logs:/var/log/postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure

volumes:
  postgres-data:
  postgres-logs:
